-- =====================================================
-- Workers Table Schema
-- Tracks system users employed under a business
-- =====================================================

-- Workers table for system users employed under a business
CREATE TABLE IF NOT EXISTS workers (
    worker_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    full_name VARCHAR(200) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone_number VARCHAR(20),
    id_card_front_url TEXT, -- Front side of ID card image
    id_card_back_url TEXT, -- Back side of ID card image
    monthly_salary DECIMAL(10,2),
    total_revenue_generated DECIMAL(12,2) DEFAULT 0,
    recent_login_history JSONB, -- Store recent login timestamps as JSON
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Comments for documentation
COMMENT ON TABLE workers IS 'Tracks system users employed under a business';
COMMENT ON COLUMN workers.worker_id IS 'Unique identifier for each worker';
COMMENT ON COLUMN workers.full_name IS 'Full name of the worker';
COMMENT ON COLUMN workers.email IS 'Worker email address for login';
COMMENT ON COLUMN workers.phone_number IS 'Worker phone number';
COMMENT ON COLUMN workers.id_card_front_url IS 'URL to front side of ID card image';
COMMENT ON COLUMN workers.id_card_back_url IS 'URL to back side of ID card image';
COMMENT ON COLUMN workers.monthly_salary IS 'Monthly salary amount';
COMMENT ON COLUMN workers.total_revenue_generated IS 'Total revenue generated by this worker';
COMMENT ON COLUMN workers.recent_login_history IS 'JSON array of recent login timestamps';
COMMENT ON COLUMN workers.created_at IS 'Timestamp when worker record was created';

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_workers_email ON workers(email);
CREATE INDEX IF NOT EXISTS idx_workers_full_name ON workers(full_name);
CREATE INDEX IF NOT EXISTS idx_workers_phone ON workers(phone_number);

-- Row Level Security (RLS) policies
ALTER TABLE workers ENABLE ROW LEVEL SECURITY;

-- Policy: Business owners can view all workers
CREATE POLICY workers_select_all ON workers
    FOR SELECT
    USING (auth.uid() IS NOT NULL);

-- Policy: Business owners can insert worker records
CREATE POLICY workers_insert_owner ON workers
    FOR INSERT
    WITH CHECK (auth.uid() IS NOT NULL);

-- Policy: Business owners can update worker records
CREATE POLICY workers_update_owner ON workers
    FOR UPDATE
    USING (auth.uid() IS NOT NULL);

-- Policy: Business owners can delete worker records
CREATE POLICY workers_delete_owner ON workers
    FOR DELETE
    USING (auth.uid() IS NOT NULL);

-- Sample data for development
INSERT INTO workers (full_name, email, phone_number, monthly_salary, total_revenue_generated) VALUES
('Jane Doe', 'jane@aquafresh.com', '+1-555-0001', 3000.00, 15000.00),
('Mike Johnson', 'mike@aquafresh.com', '+1-555-0002', 2800.00, 12500.00)
ON CONFLICT (email) DO NOTHING;
